# Generated by Django 5.0.6 on 2024-08-01 11:15

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_diseaseinfo_options_diseaseinfo_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseinfo',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='diseaseinfo',
            name='solution',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
